version: '3'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"

  nodejs:
    build:
      context: .  # ใช้ context ของโฟลเดอร์นี้
      dockerfile: Dockerfile  # ชื่อไฟล์ Dockerfile
    container_name: nodejs
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"

volumes:
  caddy_data:
  caddy_config:
